PATH_LENGTH = 100
PATH_STEP_SIZE = 1
PATH_MIN_HEIGHT = 1
PATH_MAX_HEIGHT = 5

D2GOAL_BIN_RES = 10

MIN_VEL = 1
MAX_VEL = 10

NUM_PASSES_FOR_LEARNING = 1

NUM_RANDOM_PATHS = 30
NUM_RANDOM_VELOCITY_PROFILES = 30
NUM_TRAINING_SETS =  NUM_RANDOM_PATHS*NUM_RANDOM_VELOCITY_PROFILES

VELOCITY_DYNAMICS_NOISE_AMP = 1